version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
    networks:
      - internal

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - internal
    depends_on:
      - mongodb

  donation:
    container_name: "backend"
    command: "java -jar ./target/DonationAdver-0.0.1-SNAPSHOT.jar"
    build: ./proiect_idp-main
    ports:
     - 8080:8080
    networks:
      - internal

  frontend:
    container_name: "frontend"
    build: ./proiect_idp-master
    ports:
     - 3000:3000
    networks:
      - internal
      
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    hostname: rabbitmq

  kong:
    image: kong:latest
    volumes:
        - ./Kong:/usr/local/kong/declarative
    environment:
        KONG_DATABASE: 'off'
        KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
        KONG_PROXY_ACCESS_LOG: /dev/stdout
        KONG_ADMIN_ACCESS_LOG: /dev/stdout
        KONG_PROXY_ERROR_LOG: /dev/stderr
        KONG_ADMIN_ERROR_LOG: /dev/stderr
        KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
        - 80:8000
        - 443:8443
        - 8001:8001
        - 8444:8444
    deploy:
        placement:
            constraints: [node.role == manager]
    networks:
        - internal
        - logging

  grafana:
      image: grafana/grafana:latest
      volumes:
        - ./grafana/data:/var/lib/grafana
      ports:
        - 4500:3000
      networks:
        - logging
    
  prometheus:
      image: prom/prometheus
      volumes:
        - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
      ports:
        - 9090:9090
      networks:
        - logging


volumes:
  data: {}

networks:
  internal:
  logging: